### ISSUE TITLE
Problems running examples

### ISSUE THREAD

**Issue by gomezzz** [MichelleLochner/astronomaly#56]
Hi @MichelleLochner 

I am trying out the examples but receive the following error

```
Traceback (most recent call last):
  File "astronomaly/frontend/run_server.py", line 1, in <module>
    from flask import Flask, render_template, request, Response
  File "C:\mamba\envs\astronomaly\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\mamba\envs\astronomaly\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\mamba\envs\astronomaly\lib\site-packages\itsdangerous\__init__.py)
```

I am on windows, and set up the environment with conda/mamba using

```bash
conda env create -f astronomaly_env.yml
conda activate astronomaly
pip install .
```

and then ran

```bash
python astronomaly/frontend/run_server.py astronomaly/scripts/galaxy_zoo_example.py
```

I wonder if maybe it is due to fixed version pinning in the `astronomaly_env.yml`?  (seems in the requirements.txt it is `>=` not `=`).

Creating an environment with not-fixed versions solved the above problem. However, then I ran into the same problem as described in #25 , I think that problem still persists if you clone the repo as is?

I'd be happy to create a PR for both things :v: Maybe the scripts folder needs to be moved somewhere else? Not quite sure how it should be for that.

**Comment by MichelleLochner** [comment]
Hi @gomezzz, indeed I never use conda anymore so the yml is out of data relative to the requirements file. I'll update it, but I'm hesitant to try to support conda. You're really on your own there. :)

Regarding the other error, did you run `pip install . -e`? It shouldn't have a problem with the relative import as long as you're in the top level `astronomaly` folder. I'm not sure how to reproduce it.

**Comment by MichelleLochner** [comment]
Ok I naughtily pushed straight to main. I found out you can just reference the requirements file directly in the yml, although that's far less than ideal because you probably want to install the conda packages where available rather than pip. Please try it and see if it works, if not I'd certainly welcome a PR with an updated yml!
